[preface]
== Préface

=== Écrire le livre sur Bitcoin

(((&quot;bitcoin&quot;, &quot;bénéfices de&quot;, id=&quot;BCbasicbenefits0&quot;)))(((&quot;systèmes décentralisés&quot;, &quot;bitcoin comme&quot;)))Je suis tombé sur bitcoin pour la première fois à la mi-2011. Ma réaction immédiate a été plus ou moins &quot;Pfft ! Nerd money !&quot; et je l&#39;ai ignoré pendant encore six mois, n&#39;en saisissant pas l&#39;importance. C&#39;est une réaction que j&#39;ai vue se répéter chez bon nombre des personnes les plus intelligentes que je connaisse, ce qui me réconforte un peu. La deuxième fois que je suis tombé sur bitcoin, lors d&#39;une discussion sur une liste de diffusion, j&#39;ai décidé de lire le livre blanc écrit par Satoshi Nakamoto pour étudier la source faisant autorité et voir de quoi il s&#39;agissait. (((&quot;monnaies numériques&quot;, &quot;bitcoin vs. autres&quot;)))Je me souviens encore du moment où j&#39;ai fini de lire ces neuf pages, quand j&#39;ai réalisé que le bitcoin n&#39;était pas simplement une monnaie numérique, mais un réseau de confiance qui pouvait aussi fournir la base de bien plus que de simples devises. La prise de conscience que &quot;ce n&#39;est pas de l&#39;argent, c&#39;est un réseau de confiance décentralisé&quot;, m&#39;a lancé dans un voyage de quatre mois pour dévorer toutes les informations sur le bitcoin que j&#39;ai pu trouver. Je suis devenu obsédé et captivé, passant 12 heures ou plus par jour collé à un écran, lisant, écrivant, codant et apprenant autant que possible. Je suis sorti de cet état de fugue, plus de 20 livres en moins à cause du manque de repas réguliers, déterminé à me consacrer au travail sur le bitcoin.

Deux ans plus tard, après avoir créé un certain nombre de petites entreprises en démarrage (start-ups) pour explorer divers services et produits liés au bitcoin, j&#39;ai décidé qu&#39;il était temps d&#39;écrire mon premier livre. Bitcoin était le sujet qui m&#39;avait poussé dans une frénésie de créativité et consommé mes pensées; c&#39;était la technologie la plus excitante que j&#39;avais rencontrée depuis Internet. Il était maintenant temps de partager ma passion pour cette technologie incroyable avec un public plus large.

=== Public visé

(((&quot;audience visée&quot;)))Ce livre est principalement destiné aux codeurs. Si vous pouvez utiliser un langage de programmation, ce livre vous apprendra comment fonctionnent les monnaies cryptographiques, comment les utiliser et comment développer des logiciels qui fonctionnent avec elles. Les premiers chapitres conviennent également comme une introduction approfondie au bitcoin pour les non-codeurs, tel ceux qui veulent comprendre le fonctionnement interne du bitcoin et des cryptomonnaies.

=== Pourquoi y a-t-il des insectes sur la couverture ?

(((&quot;systèmes décentralisés&quot;, &quot;dans la nature&quot;)))La fourmi coupeuse de feuilles est une espèce qui présente un comportement très complexe dans un super-organisme de colonie, mais chaque fourmi individuelle fonctionne selon un ensemble de règles simples dictées par l&#39;interaction sociale et l'échange d&#39;odeurs chimiques (phéromones). Par Wikipedia : &quot;À côté des humains, les fourmis coupeuses de feuilles forment les sociétés animales les plus grandes et les plus complexes sur Terre.&quot; Les fourmis coupeuses de feuilles ne mangent pas réellement les feuilles, mais les utilisent plutôt pour cultiver un champignon, qui est la principale source de nourriture de la colonie. Imaginez, ces fourmis cultivent !

Bien que les fourmis forment une société basée sur les castes et aient une reine pour produire une progéniture, il n&#39;y a pas d&#39;autorité centrale ou de chef dans une colonie de fourmis. Le comportement hautement intelligent et sophistiqué présenté par une colonie de plusieurs millions de membres est une propriété émergente de l&#39;interaction des individus dans un réseau social.

La nature démontre que les systèmes décentralisés peuvent être résilients et peuvent produire une complexité émergente et une sophistication incroyable sans avoir besoin d&#39;une autorité centrale, d&#39;une hiérarchie ou de parties complexes.

(((&quot;systèmes décentralisés&quot;, &quot;avantages de&quot;)))Bitcoin est un réseau de confiance décentralisé hautement sophistiqué qui peut prendre en charge une myriade de processus financiers. Pourtant, chaque nœud du réseau Bitcoin suit quelques règles mathématiques simples. L&#39;interaction entre de nombreux nœuds est ce qui conduit à l&#39;émergence du comportement sophistiqué, et non une complexité inhérente ou une confiance dans un seul nœud. Comme une colonie de fourmis, le réseau Bitcoin est un réseau résilient de nœuds simples suivant des règles simples qui, ensemble, peuvent faire des choses incroyables sans aucune coordination centrale.(((&quot;&quot;, startref=&quot;BCbasicbenefits0&quot;)))

=== Conventions utilisées dans ce livre

(((&quot;conventions typographiques&quot;)))Les conventions typographiques suivantes sont utilisées dans ce livre :

_Italique_:: Indique de nouveaux termes, URL, adresses e-mail, noms de fichiers et extensions de fichiers.

+Largeur constante+:: Utilisé pour les listes de programmes, ainsi que dans les paragraphes pour faire référence à des éléments de programme tels que des noms de variables ou de fonctions, des bases de données, des types de données, des variables d&#39;environnement, des instructions et des mots-clés.

**`Largeur constante en gras`**:: Affiche les commandes ou tout autre texte qui doit être saisi littéralement par l&#39;utilisateur.

_++Largeur constante en italique++_:: Affiche le texte qui doit être remplacé par des valeurs fournies par l&#39;utilisateur ou par des valeurs déterminées par le contexte.


[TIP]
====
Cette icône signifie un conseil ou une suggestion.
====

[NOTE]
====
Cette icône signifie une note générale.
====

[WARNING]
====
Cette icône indique un avertissement ou une mise en garde.
====

=== Exemples de codes

(((&quot;exemples de code, obtention et utilisation&quot;, id=&quot;codeuse00&quot;)))Les exemples sont illustrés en Python, C++, et en utilisant la ligne de commande d&#39;un système d&#39;exploitation de type Unix tel que Linux ou macOS. Tous les extraits de code sont disponibles dans le référentiel GitHub (https://github.com/bitcoinbook/bitcoinbook[https://github.com/bitcoinbook/bitcoinbook]) dans le sous-répertoire _code_ du référentiel principal. Fourchez le code du livre, essayez les exemples de code ou soumettez des corrections via GitHub.

Tous les extraits de code peuvent être répliqués sur la plupart des systèmes d&#39;exploitation avec une installation minimale de compilateurs et d&#39;interpréteurs pour les langages correspondants. Si nécessaire, nous fournissons des instructions d&#39;installation de base et des exemples étape par étape de la sortie de ces instructions.

Certains des extraits de code et des sorties de code ont été reformatés pour l&#39;impression. Dans tous ces cas, les lignes ont été séparées par un caractère barre oblique inverse (\), suivi d&#39;un caractère de saut de ligne. Lors de la transcription des exemples, supprimez ces deux caractères et rejoignez les lignes à nouveau et vous devriez voir des résultats identiques comme indiqué dans l&#39;exemple.

Tous les extraits de code utilisent des valeurs réelles et des calculs lorsque cela est possible, de sorte que vous pouvez construire d&#39;exemple en exemple et voir les mêmes résultats dans n&#39;importe quel code que vous écrivez pour calculer les mêmes valeurs. Par exemple, les clés privées et les clés et adresses publiques correspondantes sont toutes réelles. Les exemples de transactions, de blocs et de références de chaîne de blocs ont tous été introduits dans la chaîne de blocs Bitcoin réelle et font partie du grand livre public, vous pouvez donc les consulter sur n&#39;importe quel système Bitcoin.

=== Utilisation des exemples de code

Ce livre est là pour vous aider à faire votre travail. En général, si un exemple de code est proposé avec ce livre, vous pouvez l&#39;utiliser dans vos programmes et votre documentation. Vous n&#39;avez pas besoin de nous contacter pour obtenir une autorisation, sauf si vous reproduisez une partie importante du code. Par exemple, écrire un programme qui utilise plusieurs morceaux de code de ce livre ne nécessite pas d&#39;autorisation. La vente ou la distribution d&#39;un CD-ROM d&#39;exemples tirés des livres d&#39;O&#39;Reilly nécessite une autorisation. Répondre à une question en citant ce livre et en citant un exemple de code ne nécessite pas d&#39;autorisation. L&#39;incorporation d&#39;une quantité importante d&#39;exemples de code de ce livre dans la documentation de votre produit nécessite une autorisation.

(((&quot;attribution&quot;)))Nous apprécions, mais n&#39;exigeons pas, l&#39;attribution. Une attribution comprend généralement le titre, l&#39;auteur, l&#39;éditeur et l&#39;ISBN. Par exemple : « _Mastering Bitcoin_ par Andreas M. Antonopoulos (O&#39;Reilly). Copyright 2017 Andreas M. Antonopoulos, 978-1-491-95438-6.

(((&quot;licences de sources libres&quot;)))Certaines éditions de ce livre sont proposées sous une licence de source libre, comme https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], auquel cas les termes de cette licence s&#39;appliquent.

Si vous pensez que votre utilisation d&#39;exemples de code ne respecte pas l&#39;utilisation équitable ou l&#39;autorisation donnée ci-dessus, n&#39;hésitez pas à nous contacter à pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Adresses et transactions Bitcoin dans ce livre

(((&quot;pour commencer&quot;, &quot;avertissements et mises en garde&quot;)))(((&quot;avertissements et mises en garde&quot;, &quot;éviter d&#39;envoyer de l&#39;argent aux adresses figurant dans le livre&quot;)))(((&quot;clés et adresses&quot;, &quot;avertissements et mises en garde&quot;)))(((&quot;transactions&quot;, &quot;avertissements et mises en garde&quot;)))(((&quot;applications chaîne de blocs&quot;, &quot;avertissements et mises en garde&quot;)))(((&quot;codes QR&quot;, &quot;avertissements et mises en garde&quot;) ))Les adresses Bitcoin, les transactions, les clés, les codes QR et les données de chaîne de blocs utilisées dans ce livre sont, pour la plupart, réelles. Cela signifie que vous pouvez parcourir la chaîne de blocs, regarder les transactions proposées en exemple, les récupérer avec vos propres scripts ou programmes, etc.

Cependant, notez que les clés privées utilisées pour construire les adresses sont soit imprimées dans ce livre, soit ont été &quot;radiées&quot;. Cela signifie que si vous envoyez de l&#39;argent à l&#39;une de ces adresses, l&#39;argent sera perdu pour toujours ou, dans certains cas, tous ceux qui peuvent lire ce livre peuvent le prendre en utilisant les clés privées imprimées dans celui-ci.

[WARNING]
====
N&#39;ENVOYEZ PAS D&#39;ARGENT AUX ADRESSES DANS CE LIVRE. Votre argent sera pris par un autre lecteur, ou perdu à jamais.(((&quot;&quot;, startref=&quot;codeuse00&quot;)))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="https://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (anciennement Safari Books Online) est une plate-forme de formation et de référence basée sur l&#39;adhésion pour les entreprises, le gouvernement, les éducateurs et les particuliers.
====

Les membres ont accès à des milliers de livres, de vidéos de formation, de parcours d&#39;apprentissage, de didacticiels interactifs et de listes de lecture sélectionnées par plus de 250 éditeurs, dont O&#39;Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que , Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley &amp; Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones &amp; Bartlett et Course Technology, entre autres.

Pour plus d&#39;informations, rendez-vous sur pass:[<a href="https://oreilly.com/safari" class="orm:hideurl"><em>https://oreilly.com/safari</em></a>].

=== Comment nous contacter

(((&quot;commentaires et questions&quot;)))(((&quot;coordonnées&quot;)))Veuillez adresser vos commentaires et questions concernant ce livre à l&#39;éditeur :

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (aux États-Unis ou au Canada)</li>
  <li>707-829-0515 (international ou local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Pour commenter ou poser des questions techniques sur ce livre, envoyez un courriel à l&#39;adresse suivante pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

Pour plus d&#39;informations sur nos livres, cours, conférences et actualités, consultez notre site Web au lien : $$https://www.oreilly.com$$[].

Retrouvez-nous sur Facebook : link:$$https://facebook.com/oreilly$$[]

Suivez-nous sur Twitter : link:$$https://twitter.com/oreillymedia$$[]

Regardez-nous sur YouTube : link:$$https://www.youtube.com/oreillymedia$$[]

[role="pagebreak-before"]
=== Contacter l&#39;auteur

Vous pouvez me contacter, Andreas M. Antonopoulos, sur mon site personnel :
link:$$https://aantonop.com/$$[]

Des informations sur _Maîtriser Bitcoin (Mastering Bitcoin en anglais)_ ainsi que l&#39;Édition Ouverte et les traductions sont disponibles sur :
link:$$https://bitcoinbook.info/$$[]

Suivez-moi sur Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Suivez-moi sur Twitter:
link:$$https://twitter.com/aantonop$$[]

Suivez-moi sur LinkedIn :
link:$$https://linkedin.com/company/aantonop$$[]

Un grand merci à tous mes mécènes qui soutiennent mon travail par des dons mensuels. Vous pouvez suivre ma page Patreon ici :
link:$$https://patreon.com/aantonop$$[]

=== Remerciements

(((&quot;reconnaissances&quot;, id=&quot;acknowledge0&quot;)))Ce livre représente les efforts et les contributions de nombreuses personnes. Je suis reconnaissant pour toute l&#39;aide que j&#39;ai reçue d&#39;amis, de collègues et même de parfaits inconnus, qui m&#39;ont rejoint dans cet effort pour écrire le livre technique définitif sur les crypto-monnaies et le bitcoin.

Il est impossible de faire une distinction entre la technologie bitcoin et la communauté bitcoin, et ce livre est autant un produit de cette communauté qu&#39;un livre sur la technologie. Mon travail sur ce livre a été encouragé, applaudi, soutenu et récompensé par toute la communauté bitcoin du tout début jusqu&#39;à la toute fin. Plus que tout, ce livre m&#39;a permis de faire partie d&#39;une merveilleuse communauté pendant deux ans et je ne vous remercierai jamais assez de m&#39;avoir accepté dans cette communauté. Il y a beaucoup trop de personnes à mentionner par leur nom - des personnes que j&#39;ai rencontrées lors de conférences, d&#39;événements, de séminaires, de rencontres, de pizzas et de petits rassemblements privés, ainsi que beaucoup qui ont communiqué avec moi par Twitter, sur reddit, sur bitcointalk. org, et sur GitHub qui ont eu un impact sur ce livre. Chaque idée, analogie, question, réponse et explication que vous trouverez dans ce livre a été à un moment donné inspirée, testée ou améliorée grâce à mes interactions avec la communauté. Merci à tous pour votre soutien; sans vous ce livre n&#39;aurait pas vu le jour. Je suis éternellement reconnaissant.

Le voyage pour devenir auteur commence bien avant le premier livre, bien sûr. Ma première langue (et ma scolarité) était le grec, j&#39;ai donc dû suivre un cours de rattrapage en anglais écrit lors de ma première année d&#39;université. Je dois remercier Diana Kordas, mon professeur d&#39;écriture d&#39;anglais, qui m&#39;a aidé à développer ma confiance et mes compétences cette année-là. Plus tard, en tant que professionnel, j&#39;ai développé mes compétences en rédaction technique sur le thème des centres de données, en écrivant pour le magazine _Network World_. Je dois remercier John Dix et John Gallant, qui m&#39;ont donné mon premier travail d&#39;écriture en tant que chroniqueur à _Network World_ et à mon éditeur Michael Cooney et mon collègue Johna Till Johnson qui ont édité mes chroniques et les ont rendues aptes à la publication. Écrire 500 mots par semaine pendant quatre ans m&#39;a donné suffisamment d&#39;expérience pour éventuellement envisager de devenir auteur.

Merci également à ceux qui m&#39;ont soutenu lorsque j&#39;ai soumis ma proposition de livre à O&#39;Reilly, en fournissant des références et en examinant la proposition. Plus précisément, merci à John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver et Jon Matonis. Remerciements particuliers à Richard Kagan et Tymon Mattoszko, qui ont révisé les premières versions de la proposition et à Matthew Taylor, qui a révisé la proposition.

Merci à Cricket Liu, auteur du titre O&#39;Reilly _DNS et BIND_, qui m&#39;a présenté O&#39;Reilly. Merci également à Michael Loukides et Allyson MacDonald de O&#39;Reilly, qui ont travaillé pendant des mois pour aider à la réalisation de ce livre. Allyson a été particulièrement patiente lorsque les délais ont été manqués et les livrables retardés alors que la vie intervenait dans notre échéancier. Pour la deuxième édition, je remercie Timothy McGovern d&#39;avoir guidé le processus, Kim Cofer d&#39;avoir patiemment édité et Rebecca Panzer d&#39;avoir illustré de nombreux nouveaux diagrammes.

Les premières ébauches des premiers chapitres ont été les plus difficiles, car le bitcoin est un sujet difficile à démêler. Chaque fois que je tirais sur un fil de la technologie bitcoin, je devais tirer sur le tout. Je me suis retrouvé coincé à plusieurs reprises et un peu découragé alors que je luttais pour rendre le sujet facile à comprendre et créer un récit autour d&#39;un sujet technique aussi dense. Finalement, j&#39;ai décidé de raconter l&#39;histoire du bitcoin à travers les histoires des personnes utilisant le bitcoin et tout le livre est devenu beaucoup plus facile à écrire. Je dois remercier mon ami et mentor, Richard Kagan, qui m&#39;a aidé à démêler l&#39;histoire et à surmonter les moments de blocage de l&#39;écrivain. Je remercie Pamela Morgan, qui a révisé les premières ébauches de chaque chapitre de la première et de la deuxième édition du livre, et a posé les questions difficiles pour les améliorer. Merci également aux développeurs du groupe San Francisco Bitcoin Developers Meetup ainsi qu&#39;à Taariq Lewis et Denise Terry pour avoir aidé à tester le premier matériel. Merci également à Andrew Naugler pour la conception infographique.

Pendant le développement du livre, j&#39;ai rendu les premières ébauches disponibles sur GitHub et j&#39;ai invité les commentaires du public. Plus d&#39;une centaine de commentaires, suggestions, corrections et contributions ont été soumis en réponse. Ces contributions sont explicitement reconnues, avec mes remerciements, dans &lt<github_contrib>&gt;. Surtout, mes sincères remerciements à mes éditeurs bénévoles de GitHub, Ming T. Nguyen (1ère édition) et Will Binns (2e édition), qui ont travaillé sans relâche pour organiser, gérer et résoudre les demandes d&#39;extraction, publier des rapports et effectuer des corrections de bogues sur GitHub.

Une fois le livre rédigé, il est passé par plusieurs séries d&#39;examens techniques. Merci à Cricket Liu et Lorne Lantz pour leur examen approfondi, leurs commentaires et leur soutien.

Plusieurs développeurs de bitcoins ont fourni des échantillons de code, des critiques, des commentaires et des encouragements. Merci à Amir Taaki et Eric Voskuil pour les extraits de code par exemple et de nombreux excellents commentaires ; Chris Kleeschulte pour sa contribution à l&#39;annexe Bitcore ; Vitalik Buterin et Richard Kiss pour leur aide avec les mathématiques des courbes elliptiques et leurs contributions au code ; Gavin Andresen pour les corrections, les commentaires et les encouragements ; Michalis Kargakis pour les commentaires, les contributions et la rédaction de btcd ; et Robin Inge pour les soumissions d&#39;errata améliorant la deuxième impression. Dans la deuxième édition, j&#39;ai de nouveau reçu beaucoup d&#39;aide de la part de nombreux développeurs de Bitcoin Core, dont Eric Lombrozo qui a démystifié le Témoin Séparé, Luke Dashjr qui a aidé à améliorer le chapitre sur les transactions, Johnson Lau qui a revu le Témoin Séparé et d&#39;autres chapitres, et bien d&#39;autres. Je dois remercier Joseph Poon, Tadge Dryja et Olaoluwa Osuntokun qui ont expliqué Lightning Network, revu mes écrits et répondu aux questions lorsque je suis resté bloqué.

Je dois mon amour des mots et des livres à ma mère, Theresa, qui m&#39;a élevé dans une maison avec des livres tapissant tous les murs. Ma mère m&#39;a également acheté mon premier ordinateur en 1982, bien qu&#39;elle se décrive comme une technophobe. Mon père, Menelaos, un ingénieur civil qui vient de publier son premier livre à 80 ans, est celui qui m&#39;a enseigné la pensée logique et analytique et l&#39;amour de la science et de l&#39;ingénierie.

Merci à tous de m&#39;avoir soutenu tout au long de ce parcours.

[[github_contrib]]
==== Version préliminaire (contributions GitHub)

De nombreux contributeurs ont proposé des commentaires, des corrections et des ajouts à la première version préliminaire sur GitHub. Merci à tous pour vos contributions à ce livre.

Voici une liste des contributeurs notables de GitHub :

////
Remerciements des contributeurs Github dans un nouveau fichier...
////
include::github_contrib.asciidoc[]